#!/bin/bash
# shellcheck source=/dev/null
# ## Detect ROS version or if both ROS1 and ROS2 are installed and get the ros path <ros_path>. 
package_name="haru_drums_ros_driver"
base_path="/opt/ros"
ros_path="$(find "$base_path" -maxdepth 1 -mindepth 1 -type d | tr " " "\n" )"
n_distros="$(wc -l <<< "$ros_path")"

if [ "$n_distros" -gt "1" ]; then
    echo "Multiple ros distros founds"
    valid="0"
    while [ "$valid" == "0" ]
    do
        echo -e "$(ls /opt/ros)\n"
        echo "Please Insert ROS 1 distro name from the above list to perform installation: "
        read -r ros_distro 
        for distro in /opt/ros/*; do if [ "$(basename "$distro")" == "$ros_distro" ]; then valid="1"; ros_path="$distro"; fi; done
    done
    echo "Package $package_name will be installed on the ros $ros_distro distro in $ros_path"
else 
  ros_distro="$(basename "$ros_path")"
fi

cd "$ros_path"/share/"$package_name" || { echo "Error looking for package installation dir in postinstallation"; exit 1; }

if [ "$ros_distro" = "noetic" ]; then
  python3 -m venv venv_drums_drivers > /dev/null
  sudo chown -R "$(whoami)" venv_drums_drivers
  source venv_drums_drivers/bin/activate
  pip3 install --upgrade pip
  pip3 install wheel
  pip install -r requirements.txt
  deactivate
fi