color_number:
  blue: 51
  green: 46
  light-blue: 45
  orange: 38
  purple: 43
  red: 49
  yellow: 48
default_port: 1
number_color:
  38: orange
  43: purple
  45: light-blue
  46: green
  48: yellow
  49: red
  51: blue
number_sound:
  38: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound7.mp3
  43: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound6.mp3
  45: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound5.mp3
  46: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound1.mp3
  48: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound3.mp3
  49: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound2.mp3
  51: /home/daiego/catkin_ws/src/haru_drums_ros_driver/src/sounds/Mii_music_sounds/sound4.mp3
